### para
model: 'PROXIMATOR'
batch_size: 50
slice_shape: [256, 256, 2]
data_chns: 'CPLX'
nr_layers: 5
nr_filters: 64
lr: 0.001
iteration: 3

### tf saver
max_keep: 50
max_epochs: 500
save_interval: 50
log_interval: 10

### data
training_data_path: /home/ague/data/gluo/dataset/brain_mat/train
testing_data_path: /home/ague/data/gluo/dataset/brain_mat/test
dataset_suffix: 'npz'
normalization: 'normalize_with_max'
num_prepare: 10
nr_thread: 1
rand_scalor: 0.8
mu: 0.03
sigma: 0.03

### gpu
nr_gpu: 2
gpu_id: '2,3'
